### ISSUE TITLE
Format Java code

### ISSUE THREAD

**Issue by cavarzan** [cavarzan/generator-android-hipster#1]
Format all code, a lot of files are with wrong code formatting.

**Comment by CSDragon** [comment]
Which format is the right format? There isn't a uniform consensus on java formatting.

**Comment by cavarzan** [comment]
@CSDragon I think that the default code formatting from Android Studio is good, since it's the official IDE.. Did you have any another option?

**Comment by CSDragon** [comment]
Personally I prefer Allman Style, but there are many different formatting styles that are all equally correct, as long as everyone is using the same style. I don't know which style Android Studio uses.

That's why you should specify which style is the one your project is using, so anyone interested in working on this project knows what you meant by "wrong formatting"

**Comment by cavarzan** [comment]
Used Android Studio default coding style format.
